# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "your-client-id"
name = "shopify-tattoo-generator"
application_url = "https://shopify-tattoo-generator.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://shopify-tattoo-generator.com/auth/callback",
  "https://shopify-tattoo-generator.com/auth/shopify/callback",
  "https://shopify-tattoo-generator.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
