# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "365fcaf87b6d251b379e772eed4e9098"
name = "ai-tattoo-generator"
application_url = "https://localhost:3458"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://localhost:3458/auth/callback",
  "https://localhost:3458/auth/shopify/callback",
  "https://localhost:3458/api/auth/callback"
]
